language: rust
git:
  submodules: false
dist: trusty
sudo: required

install:
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      autoconf-archive
      bison
      docbook-xsl
      flex
      libcap-dev
      libevtlog-dev
      libglib2.0-dev
      libivykis-dev
      libjson0-dev
      libnet1-dev
      libwrap0-dev
      pkg-config
      xsltproc

matrix:
  include:
    - rust: nightly
      env:
        - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
        - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig
        - CMAKE_C_FLAGS=-std=gnu99
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/install/syslog-ng/lib
    - rust: beta
      env:
        - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig
        - CMAKE_C_FLAGS=-std=gnu99
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/install/syslog-ng/lib
    - rust: stable
      env:
        - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig
        - CMAKE_C_FLAGS=-std=gnu99
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/install/syslog-ng/lib

before_script:
  - unset PYTHON_CFLAGS # HACK
  - cd ..
  - git clone https://github.com/balabit/syslog-ng.git
  - cd syslog-ng
  - mkdir build
  - cd build
  - >
    cmake -DCMAKE_C_FLAGS=$CMAKE_C_FLAGS
    -DENABLE_JAVA:BOOL=OFF
    -DENABLE_GRADLE:BOOL=OFF
    -DENABLE_PYTHON:BOOL=OFF
    -DCMAKE_INSTALL_PREFIX="$HOME/install/syslog-ng" ..
  - make -j install
  - cd ../..

script:
  - cd syslog-ng-rust-modules
  - mkdir build
  - cd build
  - >
    cmake -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
    -DENABLE_REGEX_PARSER=ON
    -DENABLE_PYTHON_PARSER=ON
    -DENABLE_ACTIONDB_PARSER=ON
    -DENABLE_CORRELATION_PARSER=ON ..
  - make install
  - cat CMakeCache.txt
  # find every crate (containing a Cargo.toml file) and run `cargo test` command in it
  - cd ..
  - find . -name Cargo.toml | xargs -n 1 ./cargo-test.sh
