language: rust
git:
  submodules: false
dist: trusty
sudo: required

env:
    - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig

install:
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_12.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      autoconf-archive
      bison
      docbook-xsl
      flex
      gradle-2.2.1
      libcap-dev
      libdbd-sqlite3
      libdbi0-dev
      libesmtp-dev
      libevtlog-dev
      libgeoip-dev
      libglib2.0-dev
      libhiredis-dev
      libivykis-dev
      libjson0-dev
      libnet1-dev
      libriemann-client-dev
      libwrap0-dev
      pkg-config
      sqlite3
      xsltproc

compiler:
  - clang

matrix:
  include:
    - env: B=trusty-cmake
      sudo: required
      before_script:
      script:
        - mkdir build
        - cd build
        - cmake
            -DCMAKE_C_FLAGS=-Werror
            -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
            ..
        - make -j install

before_script:
  - unset PYTHON_CFLAGS # HACK
  - cd ..
  - git clone https://github.com/balabit/syslog-ng.git
  - cd syslog-ng
  - mkdir build
  - cd build
  - >
    cmake -DENABLE_JAVA:BOOL=OFF
    -DENABLE_GRADLE:BOOL=OFF
    -DENABLE_PYTHON:BOOL=OFF
    -DCMAKE_INSTALL_PREFIX="$HOME/install/syslog-ng" ..
  - make -j install
  - cd ../../syslog-ng-rust-modules
  - mkdir build
  - cd build
  - >
    cmake -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
    -DENABLE_REGEX_PARSER=ON
    -DENABLE_PYTHON_PARSER=ON
    -DENABLE_ACTIONDB_PARSER=ON
    -DENABLE_CORRELATION_PARSER=ON ..
script:
  - make install
