
dist: trusty
sudo: required

env:
    - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig CC=clang
    - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig CC=gcc


# run builds for all the trains (and more)
matrix:
    include:
        - rust: beta
          language: rust
        - rust: nightly
          env: TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
          language: rust
        - rust: stable
          language: rust

before_script:
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf-archive bison cmake docbook-xsl flex libcap-dev libesmtp-dev libevtlog-dev libgeoip-dev libglib2.0-dev libhiredis-dev libjson0-dev libnet1-dev libpcre3-dev libssl-dev libwrap0-dev openjdk-7-jdk pkg-config python3-all-dev libpython3-dev libpython3-all-dev time xsltproc libivykis-dev libjson0-dev
  - cd ..
  - git clone https://github.com/balabit/syslog-ng.git
  - cd syslog-ng
  # - ./configure --with-ivykis=system --prefix=$HOME/install/syslog-ng --disable-python --disable-java --disable-sql --disable-amqp
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng -DENABLE_AMQP=OFF -DENABLE_JAVA=OFF -DENABLE_GRADLE=OFF -DCMAKE_C_FLAGS='-std=gnu99'
  - make -j install
  - cd ../syslog-ng-rust-modules
  - mkdir build
  - cd build
  - >
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng -DENABLE_REGEX_PARSER=ON -DENABLE_PYTHON_PARSER=ON -DENABLE_ACTIONDB_PARSER=ON -DENABLE_CORRELATION_PARSER=ON ..
script:
  - make install
