language: python
python:
#  - "2.7"
  - "3.4"
#  - "3.5"
git:
  submodules: false
dist: trusty
sudo: required

env:
  - RUST_VERSION=1.7.0
  - RUST_VERSION=nightly

install:
  - curl http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_14.04 ./" | sudo tee --append /etc/apt/sources.list.d/syslog-ng-obs.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      bison
      flex
      libcap-dev
      libevtlog-dev
      libglib2.0-dev
      libivykis-dev
      libjson0-dev
      libwrap0-dev
      pkg-config
      cmake
# copied from https://github.com/dgrunwald/rust-cpython/blob/master/.travis.yml (7c59d554ec6470963b4880345f39b5a543c00496)
  - python -c "import sysconfig; print('\n'.join(map(repr,sorted(sysconfig.get_config_vars().items()))))"
  - mkdir ~/rust-installer
  - curl -sL https://static.rust-lang.org/rustup.sh -o ~/rust-installer/rustup.sh
  - sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=$RUST_VERSION -y --disable-sudo
  - export PATH="$HOME/rust/bin:$PATH"
  - export PYTHON_LIB=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
  - find $PYTHON_LIB
  - export LIBRARY_PATH="$LIBRARY_PATH:$PYTHON_LIB"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PYTHON_LIB:$HOME/rust/lib"
  - rustc -V

matrix:
  include:
#    - rust: nightly
#      env:
#        - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
#        - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig
#        - CMAKE_C_FLAGS=-std=gnu99
#        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/install/syslog-ng/lib
#    - rust: beta
#      env:
#        - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig
#        - CMAKE_C_FLAGS=-std=gnu99
#        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/install/syslog-ng/lib
    - env:
        - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig
        - CMAKE_C_FLAGS=-std=gnu99
        - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/install/syslog-ng/lib"

before_script:
#  - unset PYTHON_CFLAGS # HACK
  - cd ..
  - git clone https://github.com/balabit/syslog-ng.git
  - cd syslog-ng
  - mkdir build
  - cd build
  - >
    cmake -DCMAKE_C_FLAGS=$CMAKE_C_FLAGS
    -DENABLE_JAVA:BOOL=OFF
    -DENABLE_GRADLE:BOOL=OFF
    -DENABLE_PYTHON:BOOL=OFF
    -DCMAKE_INSTALL_PREFIX="$HOME/install/syslog-ng" ..
  - make -j install
  - cd ../..

script:
  - cd syslog-ng-rust-modules
  - mkdir build
  - cd build
  - >
    cmake -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng
    -DENABLE_REGEX_PARSER=OFF
    -DENABLE_PYTHON_PARSER=ON
    -DENABLE_ACTIONDB_PARSER=OFF
    -DENABLE_CORRELATION_PARSER=OFF ..
  - make install
  - cat CMakeCache.txt
  # find every crate (containing a Cargo.toml file) and run `cargo test` command in it
  - cd ..
  - find . -name Cargo.toml | xargs -n 1 ./cargo-test.sh
